//! This library is generated by [`openapi-client-generator`](https://crates.io/crates/openapi-client-generator).
#![allow(non_camel_case_types)]

use serde_json::json;
use serde::{Serialize, Deserialize};
use httpclient::RequestBuilder;
pub mod model;
use crate::model::*;