//! This library is generated by [`openapi-client-generator`].
//!
//! The [`PlaidClient`] is the main entry point for this library.
#![allow(non_camel_case_types)]

use serde_json::json;
use serde::{Serialize, Deserialize};
use httpclient::RequestBuilder;