[package]
name = "libninja_mir"
version = "0.1.0"
edition = "2021"
description = "mid level ir for libninja"
license = "MIT"

[lib]
name = "mir"
path = "src/lib.rs"

[dependencies]
proc-macro2.workspace = true
openapiv3-extended.workspace = true
quote.workspace = true
