openapi: 3.0.0
info:
  title: The Plaid API
  version: 2020-09-14_1.161.5
  description: The Plaid REST API. Please see https://plaid.com/docs/api for more details.
  contact:
    name: Plaid Developer Team
    url: https://plaid.com
  termsOfService: https://plaid.com/legal/
paths:
  /link/token/create:
    post:
      tags:
        - plaid
      summary: Create Link Token
      externalDocs:
        url: /api/tokens/#linktokencreate
      operationId: linkTokenCreate
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                example-1:
                  value:
                    link_token: link-sandbox-af1a0311-da53-4636-b754-dd15cc058176
                    expiration: "2020-03-27T12:56:34Z"
                    request_id: XQVgFigpGHXkb0b
      description: |-
        The `/link/token/create` endpoint creates a `link_token`, which is required as a parameter when initializing Link. Once Link has been initialized, it returns a `public_token`, which can then be exchanged for an `access_token` via `/item/public_token/exchange` as part of the main Link flow.
        
        A `link_token` generated by `/link/token/create` is also used to initialize other Link flows, such as the update mode flow for tokens with expired credentials, or the Payment Initiation (Europe) flow.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkTokenCreateRequest'
        description: ""
components:
  schemas:
    LinkTokenCreateRequest:
      type: object
      description: LinkTokenCreateRequest defines the request schema for `/link/token/create`
      properties:
        client_name:
          type: string
          description: The name of your application, as it should be displayed in Link. Maximum length of 30 characters. If a value longer than 30 characters is provided, Link will display "This Application" instead.
        language:
          type: string
          description: |-
            The language that Link should be displayed
            Supported languages are:
            - English (`'en'`)
            - French (`'fr'`)
            - Spanish (`'es'`)
            - Dutch (`'nl'`)
            - German(`'de
            When using a Link customization, the language configured here must match the setting in the customization, or the customization will not be applied.
        webhook:
          type: string
          description: The destination URL to which any webhooks should be sent.
        access_token:
          type: string
          description: The `access_token` associated with the Item to update, used when updating or modifying an existing `access_token`. Used when launching Link in update mode, when completing the Same-day (manual) Micro-deposit flow, or (optionally) when initializing Link as part of the Payment Initiation (UK and Europe) flow.
        link_customization_name:
          type: string
          description: The name of the Link customization from the Plaid Dashboard to be applied to Link. If not specified, the `default` customization will be used. When using a Link customization, the language in the customization must match the language selected via the `language` parameter, and the countries in the customization should match the country codes selected via `country_codes`.
        redirect_uri:
          type: string
          description: A URI indicating the destination where a user should be forwarded after completing the Link flow; used to support OAuth authentication flows when launching Link in the browser or via a webview. The `redirect_uri` should not contain any query parameters. When used in Production or Development, must be an https URI. To specify any subdomain, use `*` as a wildcard character, e.g. `https://*.example.com/oauth.html`. If `android_package_name` is specified, this field should be left blank.  Note that any redirect URI must also be added to the Allowed redirect URIs list in the [developer dashboard](https://dashboard.plaid.com/team/api).
        android_package_name:
          type: string
          description: 'The name of your app''s Android package. Required if using the `link_token` to initialize Link on Android. When creating a `link_token` for initializing Link on other platforms, this field must be left blank. Any package name specified here must also be added to the Allowed Android package names setting on the [developer dashboard](https://dashboard.plaid.com/team/api). '
        institution_id:
          type: string
          description: Used for certain Europe-only configurations, as well as certain legacy use cases in other regions.
        user_token:
          type: string
          description: A user token generated using `/user/create`. Any item created during the link session will be associated with the user.
      required:
        - client_name
        - language
        - country_codes
        - user
    LinkTokenCreateRequestUser:
      type: object
      description: An object specifying information about the end user who will be linking their account.
      properties:
        client_user_id:
          type: string
          description: A unique ID representing the end user. Typically this will be a user ID number from your application. Personally identifiable information, such as an email address or phone number, should not be used in the `client_user_id`. It is currently used as a means of searching logs for the given user in the Plaid Dashboard.
        legal_name:
          type: string
          deprecated: true
          description: The user's full legal name. Currently used only to support certain legacy flows.
        name:
          description: The user's full name. Optional if using the [Identity Verification](https://plaid.com/docs/api/products/identity-verification) product; if not using Identity Verification, this field is not allowed. Users will not be asked for their name when this field is provided.
          allOf:
            - $ref: '#/components/schemas/UserName'
        phone_number:
          type: string
          description: The user's phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format. This field is optional, but required to enable the [returning user experience](https://plaid.com/docs/link/returning-user).
        phone_number_verified_time:
          format: date-time
          type: string
          description: |
            The date and time the phone number was verified in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDThh:mm:ssZ`). This field is optional, but required to enable any [returning user experience](https://plaid.com/docs/link/returning-user).
            
             Only pass a verification time for a phone number that you have verified. If you have performed verification but don’t have the time, you may supply a signal value of the start of the UNIX epoch.
            
             Example: `2020-01-01T00:00:00Z`
        email_address:
          type: string
          description: The user's email address. This field is optional, but required to enable the [pre-authenticated returning user flow](https://plaid.com/docs/link/returning-user/#enabling-the-returning-user-experience).
        email_address_verified_time:
          type: string
          format: date-time
          description: |-
            The date and time the email address was verified in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDThh:mm:ssZ`). This is an optional field used in the [returning user experience](https://plaid.com/docs/link/returning-user).
            
             Only pass a verification time for an email address that you have verified. If you have performed verification but don’t have the time, you may supply a signal value of the start of the UNIX epoch.
            
             Example: `2020-01-01T00:00:00Z`
        ssn:
          type: string
          deprecated: true
          description: To be provided in the format "ddd-dd-dddd". Not currently used.
        date_of_birth:
          type: string
          format: date
          deprecated: true
          description: To be provided in the format "yyyy-mm-dd". Not currently used.
      required:
        - client_user_id
    UserName:
      description: The full name provided by the user. If the user has not submitted their name, this field will be null. Otherwise, both fields are guaranteed to be filled.
      type: object
      properties:
        given_name:
          $ref: '#/components/schemas/GivenNameField'
        family_name:
          $ref: '#/components/schemas/FamilyNameField'
      required:
        - given_name
        - family_name
      nullable: true
    GivenNameField:
      type: string
      example: Leslie
      title: GivenName
      description: A string with at least one non-whitespace character, with a max length of 100 characters.
    FamilyNameField:
      type: string
      example: Knope
      title: FamilyName
      description: A string with at least one non-whitespace character, with a max length of 100 characters.